// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace main {
    export class Config {
        serverUrl!: string;
        username!: string;
        syncDir!: string;
        autoStart!: boolean;
        syncStrategy!: string;
        lastSyncTime!: string;
        autoSync!: boolean;
        syncInterval!: number;

        constructor(source: object = {}) {
            if ('serverUrl' in source) this.serverUrl = source['serverUrl'] as string;
            if ('username' in source) this.username = source['username'] as string;
            if ('syncDir' in source) this.syncDir = source['syncDir'] as string;
            if ('autoStart' in source) this.autoStart = source['autoStart'] as boolean;
            if ('syncStrategy' in source) this.syncStrategy = source['syncStrategy'] as string;
            if ('lastSyncTime' in source) this.lastSyncTime = source['lastSyncTime'] as string;
            if ('autoSync' in source) this.autoSync = source['autoSync'] as boolean;
            if ('syncInterval' in source) this.syncInterval = source['syncInterval'] as number;
        }
    }

    export class TestResult {
        ok!: boolean;
        msg!: string;

        constructor(source: object = {}) {
            if ('ok' in source) this.ok = source['ok'] as boolean;
            if ('msg' in source) this.msg = source['msg'] as string;
        }
    }
}
