// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { main, auth, api } from '../models';

export function CheckAuth(): Promise<boolean>;

export function GetCurrentUser(): Promise<auth.UserInfo | null>;

export function Greet(arg1: string): Promise<string>;

export function IsFirstRun(): Promise<boolean>;

export function ListFiles(arg1: string): Promise<api.FileRecord[]>;

export function LoadConfig(): Promise<main.Config>;

export function Login(arg1: string, arg2: string): Promise<void>;

export function Logout(): Promise<void>;

export function SaveConfig(arg1: main.Config): Promise<void>;

export function SelectDirectory(): Promise<string>;

export function TestConnection(arg1: string): Promise<main.TestResult>;
