// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth() {
    return window['go']['main']['App']['CheckAuth']();
}

export function GetCurrentUser() {
    return window['go']['main']['App']['GetCurrentUser']();
}

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function IsFirstRun() {
    return window['go']['main']['App']['IsFirstRun']();
}

export function ListFiles(arg1) {
    return window['go']['main']['App']['ListFiles'](arg1);
}

export function LoadConfig() {
    return window['go']['main']['App']['LoadConfig']();
}

export function Login(arg1, arg2) {
    return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
    return window['go']['main']['App']['Logout']();
}

export function SaveConfig(arg1) {
    return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
    return window['go']['main']['App']['SelectDirectory']();
}

export function TestConnection(arg1) {
    return window['go']['main']['App']['TestConnection'](arg1);
}
