// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { main } from '../models';

export function Greet(arg1: string): Promise<string>;

export function IsFirstRun(): Promise<boolean>;

export function LoadConfig(): Promise<main.Config>;

export function SaveConfig(arg1: main.Config): Promise<void>;

export function SelectDirectory(): Promise<string>;

export function TestConnection(arg1: string): Promise<main.TestResult>;
