// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function IsFirstRun() {
    return window['go']['main']['App']['IsFirstRun']();
}

export function LoadConfig() {
    return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
    return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
    return window['go']['main']['App']['SelectDirectory']();
}

export function TestConnection(arg1) {
    return window['go']['main']['App']['TestConnection'](arg1);
}
